// <auto-generated />
using System;
using MISOQueryingApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MISOQueryingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MISOQueryingApp.Database.Models.FuelMixElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MegaWatts")
                        .HasColumnType("int");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("SnapshotId");

                    b.ToTable("FuelMixElements");
                });

            modelBuilder.Entity("MISOQueryingApp.Database.Models.FuelMixSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("IntervalEst")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalMegaWatts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntervalEst")
                        .IsUnique();

                    b.ToTable("FuelMixSnapshots");
                });

            modelBuilder.Entity("MISOQueryingApp.Database.Models.FuelMixElement", b =>
                {
                    b.HasOne("MISOQueryingApp.Database.Models.FuelMixSnapshot", null)
                        .WithMany("FuelMixElements")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MISOQueryingApp.Database.Models.FuelMixSnapshot", b =>
                {
                    b.Navigation("FuelMixElements");
                });
#pragma warning restore 612, 618
        }
    }
}
